name: Update default_config

on:
  workflow_dispatch:
    branches:
      - main

concurrency:
  group: "${{ github.workflow }}@${{ github.ref_name }}"
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest

    permissions: write-all

    steps:
      - name: "Checkout ${{ github.head_ref }}"
        uses: actions/checkout@v3
        with:
          ref: ${{ github.head_ref }}
          path: "clone"

      - name: "Checkout Git https://github.com/home-assistant/core/"
        uses: actions/checkout@v3
        with:
          repository: "home-assistant/core"
          path: "core"

      - name: Copy files from core repository
        shell: bash
        run: |
          rm -rf clone/custom_components
          mkdir -p clone/custom_components
          cp -Rvpf core/homeassistant/components/default_config clone/custom_components/
          sed -i '2i \  "version": "1.0.0.0",' clone/custom_components/default_config/manifest.json
          sed -i '/cloud/d' clone/custom_components/default_config/manifest.json
          rm -rf core

      - name: Save changes
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: Apply default_config changes
          repository: clone
