name: Update default_config

on:
  workflow_dispatch:
    branches:
      - main
  push:
    branches:
      - main
  schedule:
    - cron: "0 0 * * *"

concurrency:
  group: "${{ github.workflow }}@${{ github.ref_name }}"
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest

    permissions: write-all

    steps:
      - name: "Checkout ${{ github.head_ref }}"
        uses: actions/checkout@v3
        with:
          ref: ${{ github.head_ref }}
          path: "clone"

      - name: "Checkout Git https://github.com/home-assistant/core/"
        uses: actions/checkout@v3
        with:
          repository: "home-assistant/core"
          path: "core"

      - name: Update files via script
        shell: bash
        run: "clone/bin/update.sh"

      # - name: HACS Action
      #   uses: "hacs/action@main"
      #   with:
      #     category: "integration"

      # - name: Home Assistant 'hassfest' Action
      #   uses: "home-assistant/actions/hassfest@master"

      - uses: cardinalby/git-get-release-action@v1
        env:
          GITHUB_TOKEN: ${{ github.token }}
        with:
          repo: home-assistant/core
          releaseNameRegEx: '^(0|[1-9]\d*)\.(0|[1-9]\d*)\.(0|[1-9]\d*)'
        id: latest_tag

      - uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: Apply default_config changes
          repository: clone
          tagging_message: "${{ steps.latest_tag.outputs.name }}"
